version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/gatsby-theme-core'
    update_schedule: 'daily'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'all'
    version_requirement_updates: 'increase_versions'
